# Generated by Django 4.1.13 on 2024-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeschedule',
            name='end_time_local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storeschedule',
            name='start_time_local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='timestamp_utc',
            field=models.CharField(max_length=50),
        ),
    ]
