# Generated by Django 4.1.13 on 2024-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_storeschedule_end_time_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('report_url', models.FileField(blank=True, null=True, upload_to='reports')),
            ],
        ),
    ]
